### PR TITLE
Added function azure_vm_set_disablebootdiagnostic and azure_vm_set_bootdiagnosticsstorage

### PR DESCRIPTION
**Pull request by lborguetti**
We need to  use Premium Storage

### CODE REVIEW

**Comment by tiago4orion** [comment]
We need a better naming convention...

**Comment by lborguetti** [comment]
Yes, sorry for merge this before review ;(

**Comment by tiago4orion** [comment]
No problem.

**Comment by katcipis** [comment]
we really cant do something like:

azure_vm_set_boot_diagnostics_storage 

?

I like to avoid the underscores...but this seems a little excessive =/

**Comment by tiago4orion** [comment]
The first problem is that name says "set", but function only "enables the boot diagnostics", there's no value being set. 

Second problem is name lengthy. That's really hard to solve without improving nash package support.

@katcipis I'd rather yours than current. 

What do you guys think of:

```sh
fn azure_enable_storage_debug(instance) {}
fn azure_disable_storage_debug(instance) {}
``` 
When we fix nash, it would be very nice:

```sh
import "github.com/NeowayLabs/klb/azure/vm"

vm.enableStorageDebug($obj)
vm.disableStorageDebug($obj)
```

**Comment by katcipis** [comment]
@tiago4orion I like both your suggestions :+1: 

We could apply the first one right away and fix nash ASAP

**Pull request merged**
